const fs = require("fs");
const path = require("path");

const tinify = require("tinify");

const compressed = require("./src/data/compressed.js");

// Load up environment variables
require("dotenv").config();

// Constants
// ----------------------------------------------------------------------------
const IMAGES_PATH = path.resolve(__dirname, "src", "images");
const COMPRESSED_PATH = path.resolve(__dirname, "src", "data", "compressed.js");
const SUCCESS_KEY = "succeeded";
const FAILED_KEY = "failed";

// Helpers
// ----------------------------------------------------------------------------
const getImageUrls = (data) => {
  const urls = data.entries.map((x) => x.imageURL).filter((x) => x);
  return [...new Set(urls)];
};

// 'https://storage.googleapis.com/media.getbitesnap.com/prod/media/ad/94/b9e0231e449987c56f15aaa7701b.jpeg'
// Becomes
// ad94b9e0231e449987c56f15aaa7701b.jpeg
const getImageId = (url) => url.split("/media/")[1].replace(/\//g, "");

const onCompressError = (err, url) => {
  let detail;
  if (err instanceof tinify.AccountError) {
    detail = `The error message is: ${err.message}. Verify your API key and account limit.`;
  } else if (err instanceof tinify.ClientError) {
    detail = "Check your source image and request options.";
  } else if (err instanceof tinify.ServerError) {
    detail = "Temporary issue with the Tinify API.";
  } else if (err instanceof tinify.ConnectionError) {
    detail = "A network connection error occurred.";
  } else {
    detail = "Something else went wrong, unrelated to the Tinify API";
  }
  console.log(`Error compressing ${url}! Details: ${detail}`);
};

const compressImage = ({ url, id }) => {
  console.log(`\nCompressing ${url}\n`);

  const outputPath = path.join(IMAGES_PATH, id);
  console.log(outputPath);
  return new Promise((resolve, reject) => {
    tinify.fromUrl(url).toFile(outputPath, (err) => {
      if (err) {
        console.log(err);
        reject(err, url);
      } else {
        resolve(outputPath);
      }
    });
  })
    .then((filename) => {
      console.log(`Successful compressed ${url}, saved to ${filename}`);
      return { url, success: SUCCESS_KEY };
    })
    .catch((err) => {
      onCompressError(err, url);
      return { url, success: FAILED_KEY };
    });
};

const generateCompressedModule = (processed) => {
  const imageCount = fs.readdirSync(IMAGES_PATH).length;
  const imageStr = fs
    .readdirSync(IMAGES_PATH)
    .map((name) => `'${name}'`)
    .join(", ");
  const content = `// AUTOGENERATED FILE (from compress.js)
// DO NOT MANUALLY UPDATE THIS FILE
// ---------------------------------------------------------------------------

module.exports = [${imageStr}];
`;
  fs.writeFileSync(COMPRESSED_PATH, content);
  return [processed, imageCount];
};

const logOutput = (ids, skipCount, processed, imageCount) => {
  const output = `
-------------------- Output -------------------- 
Urls read: ${ids.length}
Urls skipped: ${skipCount}
Urls processed: ${processed[SUCCESS_KEY].length + processed[FAILED_KEY].length}
Urls succeded: ${processed[SUCCESS_KEY].length}
Urls failed: ${processed[FAILED_KEY].length}
Urls failed list: ${processed[FAILED_KEY].map((x) => x)}
------------------------------------------------ 

Total compressed images: ${imageCount}
Compression count for this month: ${tinify.compressionCount}
`;
  console.log(output);
};

// Main
// ----------------------------------------------------------------------------

// Auth w/ TinyPNG
const apiKey = process.env.TINY_PNG_API_KEY;
if (!apiKey) {
  console.log(`Error! TINY_PNG_API_KEY is ${apiKey} -- set it in .env`);
  process.exit(1);
}
tinify.key = apiKey;

const compressedSet = new Set(compressed);
const dataPath = path.resolve(__dirname, "src", "data", "sample.json");
const rawData = JSON.parse(fs.readFileSync(dataPath, "utf8"));
const ids = getImageUrls(rawData).map((url) => ({ url, id: getImageId(url) }));
const skipCount = ids.filter((x) => compressedSet.has(x.id)).length;

const idsToProcess = ids
  .filter((x) => !compressedSet.has(x.id))
  .map((x) => compressImage(x));
Promise.all(idsToProcess)
  // Create results map
  .then((results) =>
    results.reduce(
      (xs, x) => {
        console.log(x);
        const key = x.success;
        xs[key].push(x.url);
        return xs;
      },
      { [SUCCESS_KEY]: [], [FAILED_KEY]: [] }
    )
  )
  .then((processed) => generateCompressedModule(processed))
  .then(([processed, imageCount]) =>
    logOutput(ids, skipCount, processed, imageCount)
  )
  .then(() => process.exit(0));
